"""
DocForge CLI — Foxit Document Generation API client.

Uses the synchronous GenerateDocumentBase64 endpoint:
  POST {HOST}/document-generation/api/GenerateDocumentBase64

Request body:
  {
    "outputFormat": "pdf",
    "documentValues": { ... },
    "base64FileString": "<base64-encoded .docx template>"
  }

Response (JSON):
  {
    "message": "success",
    "fileExtension": ".pdf",
    "base64FileString": "<base64-encoded PDF>"
  }
"""

import base64
import io
from typing import Any

import httpx
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from app.foxit.auth import FoxitCredentials
from app.utils.logging import logger, step_timer


def _build_docx_template(data: dict[str, Any]) -> bytes:
    """
    Programmatically build a Word document (.docx) using Foxit's token syntax.

    Tokens:  {{ field_name }}
    Tables:  {{TableStart:array}} ... {{TableEnd:array}}
    """
    doc = Document()

    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(10)

    # --- Title ---
    title = doc.add_heading(level=0)
    run = title.add_run("{{ product_name }} — Release Notes v{{ version }}")
    run.font.size = Pt(22)
    run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = subtitle.add_run("Release Date: {{ release_date }}")
    run.font.size = Pt(11)
    run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    doc.add_paragraph("")

    # --- Summary ---
    doc.add_heading("Summary", level=1)
    doc.add_paragraph("{{ summary }}")
    doc.add_paragraph("")

    # --- Features ---
    doc.add_heading("New Features", level=1)
    if data.get("features"):
        table = doc.add_table(rows=1, cols=2)
        table.style = "Light Grid Accent 1"
        hdr = table.rows[0].cells
        hdr[0].text = "Feature"
        hdr[1].text = "Description"
        row = table.add_row().cells
        row[0].text = "{{TableStart:features}}{{ title }}"
        row[1].text = "{{ description }}{{TableEnd:features}}"
    else:
        doc.add_paragraph("None")
    doc.add_paragraph("")

    # --- Fixes ---
    doc.add_heading("Bug Fixes", level=1)
    if data.get("fixes"):
        table = doc.add_table(rows=1, cols=3)
        table.style = "Light Grid Accent 1"
        hdr = table.rows[0].cells
        hdr[0].text = "ID"
        hdr[1].text = "Title"
        hdr[2].text = "Description"
        row = table.add_row().cells
        row[0].text = "{{TableStart:fixes}}{{ id }}"
        row[1].text = "{{ title }}"
        row[2].text = "{{ description }}{{TableEnd:fixes}}"
    else:
        doc.add_paragraph("None")
    doc.add_paragraph("")

    # --- Breaking Changes ---
    h = doc.add_heading("⚠ Breaking Changes", level=1)
    for run in h.runs:
        run.font.color.rgb = RGBColor(0xCC, 0x00, 0x00)

    if data.get("breaking_changes"):
        table = doc.add_table(rows=1, cols=3)
        table.style = "Light Grid Accent 2"
        hdr = table.rows[0].cells
        hdr[0].text = "Change"
        hdr[1].text = "Description"
        hdr[2].text = "Migration"
        row = table.add_row().cells
        row[0].text = "{{TableStart:breaking_changes}}{{ title }}"
        row[1].text = "{{ description }}"
        row[2].text = "{{ migration }}{{TableEnd:breaking_changes}}"
    else:
        doc.add_paragraph("None")
    doc.add_paragraph("")

    # --- Links ---
    doc.add_heading("Useful Links", level=1)
    if data.get("links"):
        table = doc.add_table(rows=1, cols=2)
        table.style = "Light Grid Accent 1"
        hdr = table.rows[0].cells
        hdr[0].text = "Label"
        hdr[1].text = "URL"
        row = table.add_row().cells
        row[0].text = "{{TableStart:links}}{{ label }}"
        row[1].text = "{{ url }}{{TableEnd:links}}"
    else:
        doc.add_paragraph("None")

    # --- Footer ---
    doc.add_paragraph("")
    footer_para = doc.add_paragraph()
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer_para.add_run(
        "Generated by DocForge CLI — Powered by Foxit Document Generation API"
    )
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


async def generate_pdf_from_template(
    base_url: str,
    credentials: FoxitCredentials,
    release_data: dict[str, Any],
) -> bytes:
    """
    Build a Word template from the release data, call the Foxit Document
    Generation API, and return the resulting PDF as raw bytes.
    """
    with step_timer("Build Word template"):
        docx_bytes = _build_docx_template(release_data)
        b64_template = base64.b64encode(docx_bytes).decode("utf-8")

    payload = {
        "outputFormat": "pdf",
        "documentValues": release_data,
        "base64FileString": b64_template,
    }

    endpoint = f"{base_url}/document-generation/api/GenerateDocumentBase64"

    with step_timer("Foxit Document Generation API call"):
        async with httpx.AsyncClient(timeout=120.0) as client:
            resp = await client.post(
                endpoint,
                json=payload,
                headers=credentials.as_headers(),
            )
            resp.raise_for_status()
            result = resp.json()

    if result.get("base64FileString"):
        pdf_bytes = base64.b64decode(result["base64FileString"])
        logger.info(
            "  Document Generation returned %d bytes PDF", len(pdf_bytes)
        )
        return pdf_bytes

    raise RuntimeError(
        f"Document Generation API error: {result.get('message', 'unknown')}"
    )
