"""Golden tests for template + engine combinations.

These tests verify that for known inputs, the pipeline produces
PDFs with expected structural properties (page count, sections, etc.).
They test the generation layer only (no Foxit API calls).
"""

import json
import pytest
from pathlib import Path
from app.foxit.texgen import _build_latex_source


GOLDEN_INPUT = {
    "product_name": "Acme Platform",
    "version": "2.4.0",
    "release_date": "2026-02-15",
    "summary": "Major release with new features and bug fixes.",
    "features": [
        {"title": "Dashboard", "description": "Real-time analytics dashboard"},
        {"title": "API Gateway", "description": "Rate limiting and caching"},
    ],
    "fixes": [
        {"id": "BUG-101", "title": "Login crash", "description": "Fixed intermittent crash"},
        {"id": "BUG-102", "title": "Memory leak", "description": "Resolved in cache module"},
    ],
    "breaking_changes": [
        {"title": "API v1 removed", "description": "Legacy endpoints deprecated", "migration": "Migrate to /v2/ endpoints"},
    ],
    "links": [
        {"label": "Documentation", "url": "https://docs.example.com"},
        {"label": "Changelog", "url": "https://github.com/example/changelog"},
    ],
}


class TestLatexGolden:
    """Verify LaTeX source generation produces expected structure."""

    def test_contains_product_name(self):
        src = _build_latex_source(GOLDEN_INPUT)
        assert "Acme Platform" in src

    def test_contains_version(self):
        src = _build_latex_source(GOLDEN_INPUT)
        assert "2.4.0" in src

    def test_contains_all_features(self):
        src = _build_latex_source(GOLDEN_INPUT)
        assert "Dashboard" in src
        assert "API Gateway" in src

    def test_contains_all_fixes(self):
        src = _build_latex_source(GOLDEN_INPUT)
        assert "BUG-101" in src
        assert "BUG-102" in src

    def test_contains_breaking_changes(self):
        src = _build_latex_source(GOLDEN_INPUT)
        assert "API v1 removed" in src
        assert "Migrate to" in src

    def test_contains_links(self):
        src = _build_latex_source(GOLDEN_INPUT)
        assert "docs.example.com" in src

    def test_has_document_structure(self):
        src = _build_latex_source(GOLDEN_INPUT)
        assert r"\begin{document}" in src
        assert r"\end{document}" in src
        assert r"\section*{New Features}" in src
        assert r"\section*{Bug Fixes}" in src
        assert r"\section*{" in src  # Breaking Changes section

    def test_has_header_footer(self):
        src = _build_latex_source(GOLDEN_INPUT)
        assert r"\pagestyle{fancy}" in src
        assert "Generated by DocForge" in src

    def test_has_table_structure(self):
        src = _build_latex_source(GOLDEN_INPUT)
        assert r"\begin{tabularx}" in src
        assert r"\end{tabularx}" in src


class TestEmptyInputGolden:
    """Verify graceful handling of empty/minimal inputs."""

    def test_minimal_input(self):
        src = _build_latex_source({"product_name": "Test", "version": "1.0"})
        assert r"\begin{document}" in src
        assert r"\end{document}" in src
        assert "textit" in src and "None" in src

    def test_empty_features(self):
        src = _build_latex_source({
            "product_name": "Test", "version": "1.0", "features": [],
        })
        assert "textit" in src and "None" in src

    def test_empty_all_sections(self):
        src = _build_latex_source({
            "product_name": "Test", "version": "1.0",
            "features": [], "fixes": [], "breaking_changes": [], "links": [],
        })
        assert r"\begin{document}" in src
        count_none = src.count("textit")
        assert count_none >= 3  # features, fixes, breaking, links


class TestCorpusInputs:
    """Run golden tests against the test corpus files."""

    @pytest.fixture
    def corpus_dir(self):
        return Path("tests/corpus/json")

    def test_minimal_json(self, corpus_dir):
        data = json.loads((corpus_dir / "minimal.json").read_text())
        src = _build_latex_source(data)
        assert r"\begin{document}" in src
        assert data["product_name"] in src or "Unknown" in src

    def test_unicode_heavy_json(self, corpus_dir):
        data = json.loads((corpus_dir / "unicode_heavy.json").read_text())
        src = _build_latex_source(data)
        assert r"\begin{document}" in src

    def test_empty_sections_json(self, corpus_dir):
        data = json.loads((corpus_dir / "empty_sections.json").read_text())
        src = _build_latex_source(data)
        assert r"\begin{document}" in src
